### PR TITLE
Remove ? from URL if empty query string.

### PR DESCRIPTION
**Pull request by Intregrisist**
Doing a GET req with no data will still add "?" to the URL.  This does a simple check to before adding it.

### CODE REVIEW

**Comment by MauriceButler** [comment]
Thanks @Intregrisist just so I can understand the cause and how to version the next release, was this actually causing issues for you?

or just a clean up change?

**Comment by Intregrisist** [comment]
Yes, it was breaking because the URL was no longer the same.  This happened when I upgraded from 2.3.1 to the latest 2.4.0.  Tests were expecting `GET https://mydomain.com/test` and was now receiving `GET https://mydomain.com/test?`.

**Comment by MauriceButler** [comment]
hrmm while it broke tests, "technically" most endpoints or url parsers would ignore the trailing `?`

I might make it a minor, as it is a change in functionality / bug fix but I don't think it is breaking in a way worthy of a major version bump 

Do you agree with that reasoning?

**Comment by Intregrisist** [comment]
Agreed :)

**Comment by MauriceButler** [comment]
2.5.0 is published. Thanks for the pull request.

**Pull request merged**
